# Generated by Django 3.2.20 on 2023-07-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
    ]
