# Generated by Django 3.2.20 on 2023-08-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_reservation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.IntegerField(choices=[(1, '12:00pm - 1:45pm'), (2, '2:00pm - 3:45pm'), (3, '4:00pm - 5:45pm'), (4, '6:00pm - 7:45pm'), (5, '8:00pm - 9:45pm')], default=1),
        ),
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8'), (10, '10'), (12, '12')], default=2),
        ),
    ]
