# Generated by Django 3.2.20 on 2023-08-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_remove_reservation_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='number_of_seats',
        ),
    ]
